version: '3'

services:

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    restart: always
    environment:
      DOMAINS: >-
        kaizumaki.net -> http://c4c:8000,
        mail.kaizumaki.net,
        happy-valentine.kaizumaki.net -> http://happy-valentine:8001
#        test.kaizumaki.net -> http://wp
      STAGE: 'production'
#      FORCE_RENEW: 'true'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./ssl-certs:/var/lib/https-portal
      - ../create-dialogue-django/static:/var/www/vhosts/kaizumaki.net/static
      - ../create-dialogue-django/nginx/ssl/ssl.conf:/var/lib/nginx-conf/kaizumaki.net.ssl.conf.erb:ro
#      - ../saa/wordpress:/var/www/vhosts/test.kaizumaki.net
    networks:
      - default
#      - saa_default
      - createdialoguedjango_default
      - happyvalentine_default

  mail:
    image: tvial/docker-mailserver:latest
    hostname: mail
    domainname: kaizumaki.net
    ports:
      - '25:25'
      - '143:143'
      - '587:587'
      - '993:993'
    volumes:
      - ./maildata:/var/mail
      - ./mailstate:/var/mail-state
      - ./mailconfig/:/tmp/docker-mailserver/
#      - ./ssl-certs:/etc/letsencrypt:ro
    environment:
      - ENABLE_SPAMASSASSIN=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=1
      - ONE_DIR=1
#      - SSL_TYPE=letsencrypt
      - PERMIT_DOCKER=network
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    networks:
      - default
#      - saa_default
      - createdialoguedjango_default

networks:
#  saa_default:
#    external: true
  createdialoguedjango_default:
    external: true
  happyvalentine_default:
    external: true
